# Generated by Django 6.0 on 2025-12-29 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DjangoApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="team_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="team_tasks",
                to="DjangoApp.team",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[("חדש", "חדש"), ("בתהליך", "בתהליך"), ("הושלם", "הושלם")],
                default="חדש",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_tasks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("מנהל", "מנהל"), ("עובד", "עובד")],
                default="עובד",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="team_users",
                to="DjangoApp.team",
            ),
        ),
    ]
